/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author Davide
 */
public class GraficaChat extends javax.swing.JFrame {

    private Client client;
    private DefaultListModel listModelUtentiAttivi;

    public GraficaChat(Client client) {
        initComponents();
        this.client = client;
        this.setVisible(true);
        listModelUtentiAttivi = new DefaultListModel();
    }

    public void resetMessaggi() {
        txtAreaMessaggi.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listListaUtentiAttivi = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMessaggi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaMessaggioDaInviare = new javax.swing.JTextArea();
        btnInviaMessaggio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listListaUtentiAttivi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listListaUtentiAttivi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listListaUtentiAttivi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listListaUtentiAttiviValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listListaUtentiAttivi);

        txtAreaMessaggi.setColumns(20);
        txtAreaMessaggi.setRows(5);
        jScrollPane2.setViewportView(txtAreaMessaggi);

        txtAreaMessaggioDaInviare.setColumns(20);
        txtAreaMessaggioDaInviare.setRows(5);
        jScrollPane3.setViewportView(txtAreaMessaggioDaInviare);

        btnInviaMessaggio.setText("Invia");
        btnInviaMessaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviaMessaggioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(btnInviaMessaggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInviaMessaggio)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInviaMessaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviaMessaggioActionPerformed
        String messaggio = txtAreaMessaggioDaInviare.getText().trim();
        if (!messaggio.equals("")) {
            client.sendMessaggio(messaggio);
            showMessaggio(client.getUsernameClient(), messaggio);
            txtAreaMessaggioDaInviare.setText("");
        }
    }//GEN-LAST:event_btnInviaMessaggioActionPerformed

    private void listListaUtentiAttiviValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listListaUtentiAttiviValueChanged
        int index = listListaUtentiAttivi.getSelectedIndex();
        System.out.println(Arrays.toString(listModelUtentiAttivi.toArray()));
        System.out.println("Index lista->"+index);
        
        if (index >= 0) {
            
            System.out.println("ELEMENTO ESISTE!");
            String nomeUtente = (String)listListaUtentiAttivi.getSelectedValue();
            System.out.println("scelto destinatario-> "+nomeUtente);
            client.setUtenteInVisualizzazione(nomeUtente);
        }
    }//GEN-LAST:event_listListaUtentiAttiviValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInviaMessaggio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listListaUtentiAttivi;
    private javax.swing.JTextArea txtAreaMessaggi;
    private javax.swing.JTextArea txtAreaMessaggioDaInviare;
    // End of variables declaration//GEN-END:variables

    public void updateListaUtentiAttivi() {
        listModelUtentiAttivi.removeAllElements();
        String[] utenti = client.getListaUtentiAttivi();
        System.out.println("");
        for (String conversazione : utenti) {
            listModelUtentiAttivi.addElement(conversazione);
            System.out.println("INSERITO IN JLIST-> "+conversazione);
        }
        listListaUtentiAttivi.setModel(listModelUtentiAttivi);
        
        
    }

    public void showMessaggio(String mittente, String messaggio) {
        String messaggi = txtAreaMessaggi.getText();
        messaggi = messaggi + mittente + "\n" + messaggio + "\n\n";
        txtAreaMessaggi.setText(messaggi);
    }
}
