/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientchat;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import oggetti.Messaggio;

/**
 *
 * @author MATTI
 */
public class Accesso extends JFrame implements Observer {

    private Service service;

    public Accesso(Service ser) {
        System.out.println("inizio c");
        initComponents();
        suggerimento.setForeground(Color.red);
        service = ser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        nomeUtente = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        accedi = new javax.swing.JButton();
        utenteNonRegistrato = new javax.swing.JLabel();
        suggerimento = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Benvenuto in MyChat!");

        lNome.setText("Nome Utente");

        nomeUtente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeUtenteFocusGained(evt);
            }
        });

        lPassword.setText("Password");

        accedi.setText("Accedi");
        accedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accediMouseReleased(evt);
            }
        });

        utenteNonRegistrato.setText("Non sei registrato? Registrati");
        utenteNonRegistrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                utenteNonRegistratoMouseReleased(evt);
            }
        });

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accedi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(utenteNonRegistrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNome)
                            .addComponent(lPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeUtente)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addComponent(suggerimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(nomeUtente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suggerimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(accedi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utenteNonRegistrato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utenteNonRegistratoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utenteNonRegistratoMouseReleased
        service.doRegistrazione();
        dispose();
    }//GEN-LAST:event_utenteNonRegistratoMouseReleased

    private void accediMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accediMouseReleased
        if (suggerimento.getText().equals("Sei disconnesso dal server")) {
            service.setConnection();
        } else {
            if (nomeUtente.getText().length() > 0 && password.getText().length() > 0) {
                logIn(nomeUtente.getText(), password.getText());
            }
            if (nomeUtente.getText().length() <= 0) {
                lNome.setForeground(Color.red);
            }
            if (password.getText().length() <= 0) {
                lPassword.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_accediMouseReleased

    private void nomeUtenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeUtenteFocusGained
        lNome.setForeground(Color.BLACK);
        suggerimento.setText("");
    }//GEN-LAST:event_nomeUtenteFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        lPassword.setForeground(Color.BLACK);
        suggerimento.setText("");
    }//GEN-LAST:event_passwordFocusGained

    /**
     * @param args the command line arguments
     */


    private void logIn(String nomeUtente, String password) {
        service.accedi(nomeUtente, password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accedi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPassword;
    private javax.swing.JTextField nomeUtente;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel suggerimento;
    private javax.swing.JLabel utenteNonRegistrato;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Service my = (Service) (o);
        Messaggio msg = my.msg;
        if (msg != null) {
            switch (msg.getFunzione()) {
                case Messaggio.ACCESSO:
                    Object dati[] = (Object[]) msg.getMessaggio();
                    if (!dati[0].equals("1")) {
                        service.startChatting((String)dati[0],(byte[])dati[1]);
                        dispose();
                    } else {
                        suggerimento.setText((String)dati[1]);
                    }
                    break;
                case Messaggio.ERRORECONNESSIONE:
                    suggerimento.setText((String) msg.getMessaggio());
                    accedi.setText("Riprova connessione");
                    nomeUtente.setEnabled(false);
                    password.setEnabled(false);
                    break;
                case Messaggio.CONNESSO:
                    suggerimento.setText((String) msg.getMessaggio());
                    accedi.setText("Accedi");
                    nomeUtente.setEnabled(true);
                    password.setEnabled(true);
                    break;
                default:
                    suggerimento.setText("Errore sconosciuto");
                    break;
            }
        }
    }
}
