/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientchat;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author MATTI
 */
public class Client extends JFrame implements Observer {

    DefaultListModel<String> modello;
    private String utenteSel, nomeUtenteNow;
    private Service service;

    public Client(String utenteAttuale) {
        initComponents();
        utenteSel = "";
        modello = (DefaultListModel<String>) listaUtenti.getModel();
        this.setTitle(utenteAttuale);
        nomeUtenteNow = utenteAttuale;
        service = new Service();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminaDialog = new javax.swing.JDialog();
        messaggio = new javax.swing.JLabel();
        nomeUtenteEl = new javax.swing.JLabel();
        passwordEl = new javax.swing.JPasswordField();
        confermaBtn = new javax.swing.JButton();
        sugEl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUtenti = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputChat = new javax.swing.JTextArea();
        invio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        stato = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        aggiornaChat = new javax.swing.JButton();

        eliminaDialog.setAlwaysOnTop(true);
        eliminaDialog.setMinimumSize(new java.awt.Dimension(300, 300));
        eliminaDialog.setResizable(false);

        messaggio.setText("Ci dispiace che te ne voglia andare ");

        confermaBtn.setText("Elimina definitivamente");
        confermaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confermaBtnMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout eliminaDialogLayout = new javax.swing.GroupLayout(eliminaDialog.getContentPane());
        eliminaDialog.getContentPane().setLayout(eliminaDialogLayout);
        eliminaDialogLayout.setHorizontalGroup(
            eliminaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messaggio, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(nomeUtenteEl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminaDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confermaBtn))
                    .addGroup(eliminaDialogLayout.createSequentialGroup()
                        .addComponent(passwordEl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sugEl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        eliminaDialogLayout.setVerticalGroup(
            eliminaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messaggio)
                .addGap(18, 18, 18)
                .addComponent(nomeUtenteEl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordEl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sugEl, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(confermaBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Bentornato");

        listaUtenti.setModel(new DefaultListModel<String>() {

        }
    );
    listaUtenti.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            listaUtentiMouseClicked(evt);
        }
    });
    listaUtenti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            listaUtentiValueChanged(evt);
        }
    });
    jScrollPane1.setViewportView(listaUtenti);

    chat.setEditable(false);
    chat.setColumns(20);
    chat.setRows(5);
    jScrollPane2.setViewportView(chat);

    inputChat.setColumns(20);
    inputChat.setRows(5);
    jScrollPane3.setViewportView(inputChat);

    invio.setText("Invia");
    invio.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            invioMouseReleased(evt);
        }
    });

    jLabel3.setText("Stato:");

    stato.setText("null");

    jButton1.setText("Elimina account");
    jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jButton1MouseReleased(evt);
        }
    });

    aggiornaChat.setText("Aggiorna chat");
    aggiornaChat.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            aggiornaChatMouseReleased(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aggiornaChat)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(invio)))))
                    .addContainerGap(20, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(stato, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(invio, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                .addComponent(jScrollPane1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(stato)
                .addComponent(aggiornaChat))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaUtentiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaUtentiValueChanged

    }//GEN-LAST:event_listaUtentiValueChanged

    private void listaUtentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUtentiMouseClicked
        chat.setText("");
        utenteSel = listaUtenti.getSelectedValue();
        ArrayList<String[]> chatT = service.showChat(utenteSel);
        if (chatT.isEmpty() || chatT.get(0)[0].equals("0")) {
            chat.setText("Nessuna conversazione momentaneamente");
        } else if (chatT.get(0)[0].equals("Disconnesso")) {
            stato.setText("Oh no, sembra che il server sia disconnesso :/");
        } else {
            for (int i = 0; i < chatT.size(); i++) {
                String chatI[] = chatT.get(i);
                chat.append(chatI[0] + "\n" + chatI[2] + "\n     " + chatI[1] + "\n");
            }
        }
    }//GEN-LAST:event_listaUtentiMouseClicked

    private void invioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invioMouseReleased
        if (inputChat.getText().length() > 0 && inputChat.getText().length() < 500) {
            updateChat();
        } else {
            inputChat.setText("Inserisci almeno 1 carattere e al massimo 500");
        }
    }//GEN-LAST:event_invioMouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        service.closeConnection();
        // System.out.println("Chiuso");
    }//GEN-LAST:event_formWindowClosed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        eliminaDialog.setVisible(true);
        eliminaDialog.setAlwaysOnTop(true);
        messaggio.setText(messaggio.getText().toString() + nomeUtenteNow);
        nomeUtenteEl.setEnabled(false);
        nomeUtenteEl.setText(nomeUtenteNow);
    }//GEN-LAST:event_jButton1MouseReleased

    private void confermaBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confermaBtnMouseReleased
        sugEl.setText("");
        if (passwordEl.getText().toString().length() > 0) {
            String check = service.deleteAccount(passwordEl.getText().toString());
            if (check.contains("disconnesso")) {
                sugEl.setText("Sei disconnesso dal server");
            } else if (check.equals("false")) {
                sugEl.setText("Password errata");
            } else {
                eliminaDialog.dispose();
                dispose();
                Accesso a = new Accesso();
                a.setVisible(true);
            }
        } else {
            sugEl.setForeground(Color.red);
            sugEl.setText("Inserisci la password");
        }
    }//GEN-LAST:event_confermaBtnMouseReleased

    private void aggiornaChatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aggiornaChatMouseReleased
        updateChat();
    }//GEN-LAST:event_aggiornaChatMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiornaChat;
    private javax.swing.JTextArea chat;
    private javax.swing.JButton confermaBtn;
    private javax.swing.JDialog eliminaDialog;
    private javax.swing.JTextArea inputChat;
    private javax.swing.JButton invio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaUtenti;
    private javax.swing.JLabel messaggio;
    private javax.swing.JLabel nomeUtenteEl;
    private javax.swing.JPasswordField passwordEl;
    private javax.swing.JLabel stato;
    private javax.swing.JLabel sugEl;
    // End of variables declaration//GEN-END:variables

    private void updateChat() {
        String data = service.saveChat(inputChat.getText().toString(), utenteSel);
        if (data.equals("true")) {
            chat.setText("");
            chat.append("Tu: " + inputChat.getText() + "\n");
            inputChat.setText("");
        } else if (data.contains("disconnesso")) {
            stato.setText("Disconnesso, il messaggio non è stato inviato");
        } else {
            stato.setText("Errore sconosciuto, il messaggio non è stato inviato");
        }
    }

    @Override
    public void update(Observable o, Object arg) {
        Service my = (Service) (o);
        //System.out.println(my.connectionState());
        if (!my.connectionState()) {
            stato.setText("Disconnesso");
            invio.setEnabled(false);
            inputChat.setEnabled(false);
        } else {
            stato.setText("Connesso");
            invio.setEnabled(true);
            inputChat.setEnabled(true);
            ArrayList<String> utenti = my.getUtenti(this.getTitle());
            for (int i = 0; i < utenti.size(); i++) {
                modello.addElement(utenti.get(i));
            }
        }
    }
}
