package clientperserver;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Davide Porcu
 */
public class InterfacciaGraficaClient extends javax.swing.JFrame {

    private Client client;

    public InterfacciaGraficaClient(Client client) {
        initComponents();
        this.setLookAndFeelInfo();
        this.setTitle("Client - Davide Porcu 5IA");
        this.client = client;
        this.setVisible(true);
        this.txtAreaElencoInformazioni.setEditable(false);
    }

    public void setTextDomanda(String domanda) {
        this.lblDomanda.setText(domanda);
    }

    public void setTextElencoInformazioni(String informazioni) {
        this.txtAreaElencoInformazioni.setText(informazioni);
    }

    public void setTextErrori(String errore) {
        this.lblErrori.setText(errore);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDomanda = new javax.swing.JLabel();
        txtFldRisposta = new javax.swing.JTextField();
        lblErrori = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaElencoInformazioni = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtFldRisposta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFldRispostaKeyPressed(evt);
            }
        });

        txtAreaElencoInformazioni.setColumns(20);
        txtAreaElencoInformazioni.setRows(5);
        txtAreaElencoInformazioni.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAreaElencoInformazioni);
        txtAreaElencoInformazioni.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(txtFldRisposta)
                    .addComponent(lblErrori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblErrori, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDomanda, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldRisposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldRispostaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFldRispostaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            client.scriviAlServer(txtFldRisposta.getText());
            txtFldRisposta.setText("");
        }
    }//GEN-LAST:event_txtFldRispostaKeyPressed

    private void setLookAndFeelInfo() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InterfacciaGraficaClient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDomanda;
    private javax.swing.JLabel lblErrori;
    private javax.swing.JTextArea txtAreaElencoInformazioni;
    private javax.swing.JTextField txtFldRisposta;
    // End of variables declaration//GEN-END:variables
}
