/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Enrico
 */
public class VistaOrdiniPrenotazioni extends javax.swing.JFrame {
    
    private BufferedReader in;
    private PrintWriter out;

    /**
     * Creates new form VistaOrdiniPrenotazioni
     */
    public VistaOrdiniPrenotazioni(BufferedReader in,PrintWriter out) throws IOException {
        this.in=in;
        this.out=out;
        initComponents();
        int nOrdini=Integer.parseInt(in.readLine());
        labelOrdini.setText("<html>");
        for(int i=0;i<nOrdini;i++){
            labelOrdini.setText(labelOrdini.getText()+in.readLine() +"<br>");
            int nProdotti=Integer.parseInt(in.readLine());
            for(int j=0;j<nProdotti;j++){
                labelOrdini.setText(labelOrdini.getText()+"   "+in.readLine() +"<br>");
            }
        }
        labelOrdini.setText(labelOrdini.getText()+"</html>");
        int nPrenotazioni=Integer.parseInt(in.readLine());
        labelPrenotazioni.setText("<html>");
        for(int i=0;i<nPrenotazioni;i++){
            labelPrenotazioni.setText(labelPrenotazioni.getText()+in.readLine() +"<br>");
        }
        labelPrenotazioni.setText(labelPrenotazioni.getText()+"</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEsci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelOrdini = new javax.swing.JLabel();
        labelPrenotazioni = new javax.swing.JLabel();
        btnContatta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEsci.setText("Esci");
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });

        jLabel1.setText("ORDINI");

        jLabel2.setText("PRENOTAZIONI");

        btnContatta.setText("Contatta pizzeria");
        btnContatta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContattaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOrdini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnEsci))
                    .addComponent(btnContatta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPrenotazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsci)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelOrdini, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrenotazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContatta, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        dispose();
        out.println("");
        VistaIniziale v=new VistaIniziale(in,out);
        v.setVisible(true);
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnContattaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContattaActionPerformed
        dispose();
        out.println("contatta");
        VistaDialogo v;
        try {
            v = new VistaDialogo(in,out);
            v.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VistaOrdiniPrenotazioni.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContattaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContatta;
    private javax.swing.JButton btnEsci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelOrdini;
    private javax.swing.JLabel labelPrenotazioni;
    // End of variables declaration//GEN-END:variables
}
