/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

/**
 *
 * @author pago1
 */
public class Welcome extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_loginSelect = new javax.swing.JButton();
        btn_registerSelect = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(198, 140));
        setMinimumSize(new java.awt.Dimension(198, 140));
        setPreferredSize(new java.awt.Dimension(231, 140));

        btn_loginSelect.setText("Login");
        btn_loginSelect.setMaximumSize(new java.awt.Dimension(57, 57));
        btn_loginSelect.setMinimumSize(new java.awt.Dimension(57, 57));
        btn_loginSelect.setPreferredSize(new java.awt.Dimension(79, 57));
        btn_loginSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginSelectActionPerformed(evt);
            }
        });

        btn_registerSelect.setText("Registrati");
        btn_registerSelect.setPreferredSize(new java.awt.Dimension(79, 57));
        btn_registerSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_loginSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_registerSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_loginSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerSelectActionPerformed
        
    }//GEN-LAST:event_btn_registerSelectActionPerformed

    private void btn_loginSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginSelectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loginSelect;
    private javax.swing.JButton btn_registerSelect;
    // End of variables declaration//GEN-END:variables
}
