package client;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author Francesco Forcellato
 */
public class GraficaClient extends javax.swing.JFrame {

    private DefaultListModel m;
    private String elementoSelezionato;

    /**
     * Creates new form GClient
     */
    public GraficaClient() {
        initComponents();
        lblErrori.setVisible(false);
        pnlLista.setVisible(false);
        m = new DefaultListModel();
        lstOpzioni.setModel(m);
        elementoSelezionato = "";
    }

    public void errore(String messaggio) {
        lblErrori.setText(messaggio);
        lblErrori.setVisible(true);
    }

    public void setDomanda(String domanda) {
        lblDomanda.setText(domanda);
    }

    public void resetOpzioni() {
        m.removeAllElements();
    }

    public void addOpzione(String opzione) {
        m.addElement(opzione);
    }

    public void visibile(boolean visibile) {
        pnlLista.setVisible(visibile);
    }

    public boolean hasOpzioni() {
        return !m.isEmpty();
    }

    private void inviaAlServer() {
        try {
            Client.invio(txtRisp.getText());
            txtRisp.setText("");
        } catch (IOException ex) {
            errore(ex.getMessage());
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDomanda = new javax.swing.JLabel();
        txtRisp = new javax.swing.JTextField();
        pnlLista = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOpzioni = new javax.swing.JList<>();
        lblErrori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Client");

        lblDomanda.setText("Server");

        txtRisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRispActionPerformed(evt);
            }
        });

        lstOpzioni.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstOpzioni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstOpzioniMouseClicked(evt);
            }
        });
        lstOpzioni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lstOpzioniKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstOpzioniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstOpzioniKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lstOpzioni);

        javax.swing.GroupLayout pnlListaLayout = new javax.swing.GroupLayout(pnlLista);
        pnlLista.setLayout(pnlListaLayout);
        pnlListaLayout.setHorizontalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlListaLayout.setVerticalGroup(
            pnlListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDomanda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRisp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDomanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtRisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblErrori.setForeground(new java.awt.Color(255, 9, 0));
        lblErrori.setText("ERRORI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblErrori))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrori)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRispActionPerformed
        inviaAlServer();
    }//GEN-LAST:event_txtRispActionPerformed

    private void lstOpzioniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstOpzioniMouseClicked
        String corrente = lstOpzioni.getSelectedValue();
        if (elementoSelezionato == corrente) { // controlla se l'elemento cliccato in quel momento sia esattamente lo stesso cliccato prima
            inviaAlServer();
            elementoSelezionato = "";
        } else {
            elementoSelezionato = corrente;
            txtRisp.setText(lstOpzioni.getSelectedValue());
        }
    }//GEN-LAST:event_lstOpzioniMouseClicked

    private void lstOpzioniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstOpzioniKeyTyped
        if (evt.getKeyChar() == '\n') {
            inviaAlServer();
        }
    }//GEN-LAST:event_lstOpzioniKeyTyped

    private void lstOpzioniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstOpzioniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtRisp.setText(lstOpzioni.getSelectedValue());
        }
    }//GEN-LAST:event_lstOpzioniKeyPressed

    private void lstOpzioniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstOpzioniKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtRisp.setText(lstOpzioni.getSelectedValue());
        }
    }//GEN-LAST:event_lstOpzioniKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDomanda;
    private javax.swing.JLabel lblErrori;
    private javax.swing.JList<String> lstOpzioni;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JTextField txtRisp;
    // End of variables declaration//GEN-END:variables
}
