/**
 * @author Alvise Busetto
 * @date 01.11.2017
 */
package clientchat;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ChatHome extends javax.swing.JFrame {

    /**
     * Creates new form ChatHome
     *
     * @param socket inizializzazione del socket che verrà utilizzato da tutte
     * le classi
     * @param in bufferedReader per la lettura dei messaggi provenienti dal
     * server
     * @param out printWriter per la scrittura dei dati verso il server
     */
    Socket socket;
    private BufferedReader in;
    private PrintWriter out;

    public ChatHome() throws IOException {
        initComponents();
        refreshList();
    }

    /*
     *@brief metodo per importare gli oggetti della finestra precedente
     */
    public void set(Socket socket, PrintWriter out, BufferedReader in) {
        this.socket = socket;
        this.out = out;
        this.in = in;
    }

    /*
     *@brief metodo per popolare le label con i client connessi che verranno spediti dal server sotto forma di stringa, i vari nomi saranno separati dal carattere "§"
     *@param numLabel è un'arrey contenente tutte le labl previste dalla finestra ChatHome, ovvero 8, si prevede che non potranno collegarsi più di 8 client contemporaneamente
     */
    /*public void refreshList() throws IOException {
        String clientList = "JIM§null§null§"; // in.readLine()
        System.out.println(clientList);
        int contLabel = 0;
        int primoChar = 0;
        for (int i = 0; i < clientList.length(); i++) {
            if (clientList.charAt(i) == '§') {
                numLabel[contLabel].setText(clientList.substring(primoChar, i - 1));
                primoChar = i + 1;
            }
        }
    }*/

    public void refreshList() throws IOException {
        String clientList = in.readLine(); //viene ricevuta la stringa proveniente dal server con i vari client name 
        int contLabel = 0; //variabile per l'individuazione della label in cui inserire il client
        int primoChar = 0; //variabile necessaria per l'individuazione dei client name all'interno della stringa arrivata dal server
        for (int i = 0; i < clientList.length(); i++) {
            if (clientList.charAt(i) == '§') { //quando controllando la stringa si raggiunge un carattere di separazione si ha raggiunto la fine di un client name
                numLabel[contLabel].setText(clientList.substring(primoChar, i - 1)); //attraverso il metodo substring si recupera il nome del client partendo dall'ultima "§" sino a quella attuale, viene scritto tale nome nella label corrente
                primoChar = i + 1; //si prende nota che l'ultimo carattere era un "§" percui il prossimo client name partirà da quello + 1
                contLabel++; //si procede all'individuazione del prossimo client name, quindi cambierà la label in cui scrivere
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClient2 = new javax.swing.JButton();
        btnClient6 = new javax.swing.JButton();
        client8 = new javax.swing.JLabel();
        client4 = new javax.swing.JLabel();
        btnClient4 = new javax.swing.JButton();
        btnClient5 = new javax.swing.JButton();
        client2 = new javax.swing.JLabel();
        btnClient8 = new javax.swing.JButton();
        btnClient3 = new javax.swing.JButton();
        client7 = new javax.swing.JLabel();
        btnClient1 = new javax.swing.JButton();
        client3 = new javax.swing.JLabel();
        client5 = new javax.swing.JLabel();
        client6 = new javax.swing.JLabel();
        btnClient7 = new javax.swing.JButton();
        client1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HOME CHAT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btnClient2.setText("comincia chat");
        btnClient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient2ActionPerformed(evt);
            }
        });

        btnClient6.setText("comincia chat");
        btnClient6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient6ActionPerformed(evt);
            }
        });

        client8.setText("utente non connesso");

        client4.setText("utente non connesso");

        btnClient4.setText("comincia chat");
        btnClient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient4ActionPerformed(evt);
            }
        });

        btnClient5.setText("comincia chat");
        btnClient5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient5ActionPerformed(evt);
            }
        });

        client2.setText("utente non connesso");

        btnClient8.setText("comincia chat");
        btnClient8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient8ActionPerformed(evt);
            }
        });

        btnClient3.setText("comincia chat");
        btnClient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient3ActionPerformed(evt);
            }
        });

        client7.setText("utente non connesso");

        btnClient1.setText("comincia chat");
        btnClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient1ActionPerformed(evt);
            }
        });

        client3.setText("utente non connesso");

        client5.setText("utente non connesso");

        client6.setText("utente non connesso");

        btnClient7.setText("comincia chat");
        btnClient7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClient7ActionPerformed(evt);
            }
        });

        client1.setText("utente non connesso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(client2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClient1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(client8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(client3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClient3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClient8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClient1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(client1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClient2)
                    .addComponent(client2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClient3)
                    .addComponent(client3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClient4)
                    .addComponent(client4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClient5)
                    .addComponent(client5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(client6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClient6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClient7)
                    .addComponent(client7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClient8)
                    .addComponent(client8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     *@brief i seguenti actionPerformed fanno tutti capo ad un singolo metodo "selectChat"
     */

    private void btnClient8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient8ActionPerformed
        selectChat(7);
    }//GEN-LAST:event_btnClient8ActionPerformed

    private void btnClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient1ActionPerformed
        selectChat(0);
    }//GEN-LAST:event_btnClient1ActionPerformed

    private void btnClient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient2ActionPerformed
        selectChat(1);
    }//GEN-LAST:event_btnClient2ActionPerformed

    private void btnClient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient3ActionPerformed
        selectChat(2);
    }//GEN-LAST:event_btnClient3ActionPerformed

    private void btnClient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient4ActionPerformed
        selectChat(3);
    }//GEN-LAST:event_btnClient4ActionPerformed

    private void btnClient5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient5ActionPerformed
        selectChat(4);
    }//GEN-LAST:event_btnClient5ActionPerformed

    private void btnClient6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient6ActionPerformed
        selectChat(5);
    }//GEN-LAST:event_btnClient6ActionPerformed

    private void btnClient7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClient7ActionPerformed
        selectChat(6);
    }//GEN-LAST:event_btnClient7ActionPerformed

    /*
     *@param numBtn è il numero del bottone che viene premuto che corrisponderà ad una singola label (quindi client), ovvero la numBtn-esima cella dell'array numLabel
     *@brief il seguente metodo lancia la finestra di chat con il client selezionato tramite il clic su tale bottone, facendo attenzione che vi sia effettivamente un client collegato in tale riga
     *       inoltre viene comunicato al server con che client si vuole comunicare
     */
    public void selectChat(int numBtn) {
        if (!numLabel[numBtn].getText().equals("utente non connesso")) { //se c'è un client collegato in quella riga
            out.println(numBtn); //viene comunicato al server con che client vogliamo comunicare
            Chat chat = new Chat();
            chat.set(socket, in, out);//viene creato l'oggetto chat
            chat.setVisible(true); //viene lanciata l'interfaccia grafica di chat con tale client
            this.setVisible(false); //viene disattivata la finestra di home chat
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChatHome().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ChatHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClient1;
    private javax.swing.JButton btnClient2;
    private javax.swing.JButton btnClient3;
    private javax.swing.JButton btnClient4;
    private javax.swing.JButton btnClient5;
    private javax.swing.JButton btnClient6;
    private javax.swing.JButton btnClient7;
    private javax.swing.JButton btnClient8;
    private javax.swing.JLabel client1;
    private javax.swing.JLabel client2;
    private javax.swing.JLabel client3;
    private javax.swing.JLabel client4;
    private javax.swing.JLabel client5;
    private javax.swing.JLabel client6;
    private javax.swing.JLabel client7;
    private javax.swing.JLabel client8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel[] numLabel = {client1, client2, client3, client4, client5, client6, client7, client8}; //array di label per l'identificazione del bottone riferito alla label
}
