package clienttcp;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ChatView extends javax.swing.JFrame{
    private class Ascoltatore extends Thread {

        @Override
        public void run() {
            boolean continua = true;
            while (continua) {
                try {
                    String op = in.readLine();
                    if (op.equals("Leggi")) {
                        if (idChat == Integer.parseInt(in.readLine())) {
                            conversazione.setText(conversazione.getText() + in.readLine() + "\n\n");
                        }
                    } else if (op.equals("Rimuovi")) {
                        contattiComboBox.removeItem(in.readLine());
                    } else if (op.equals("")) {
                        continua = false;
                        dispose();
                        UserView v = new UserView(in, out);
                        v.setVisible(true);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(ChatView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private BufferedReader in;
    private PrintWriter out;
    private int idChat;

    /**
     * Creates new form VistaChat
     */
    public ChatView(BufferedReader in, PrintWriter out, int idChat) throws IOException {
        this.in = in;
        this.out = out;
        this.idChat = idChat;
        initComponents();
        out.println("Carica");
        if (in.readLine().equals("Gruppo")) {
            int nContatti = Integer.parseInt(in.readLine());
            for (int i = 0; i < nContatti; i++) {
                contattiComboBox.addItem(in.readLine());
            }
        } else {
            contattiComboBox.setVisible(false);
            btnAggiungi.setVisible(false);
        }
        int nMessaggi = Integer.parseInt(in.readLine());
        for (int i = 0; i < nMessaggi; i++) {
            String testo = in.readLine();
            conversazione.setText(conversazione.getText() + testo + "\n\n");
        }
        new Ascoltatore().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conversazione = new javax.swing.JTextArea();
        btnEsci = new javax.swing.JButton();
        messaggio = new javax.swing.JTextField();
        btnInvia = new javax.swing.JButton();
        btnAggiungi = new javax.swing.JButton();
        contattiComboBox = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        conversazione.setColumns(20);
        conversazione.setRows(5);
        jScrollPane1.setViewportView(conversazione);

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnEsci.setText("Esci");
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });

        btnInvia.setText("Invia");
        btnInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviaActionPerformed(evt);
            }
        });

        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEsci, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAggiungi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contattiComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(messaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnInvia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEsci)
                .addGap(88, 88, 88)
                .addComponent(contattiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAggiungi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messaggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvia))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        out.println("");
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviaActionPerformed
        String testo = messaggio.getText();
        conversazione.setText(conversazione.getText() + "Tu:" + testo + "\n\n");
        out.println("Invio");
        out.println(testo);
    }//GEN-LAST:event_btnInviaActionPerformed

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        if (contattiComboBox.getSelectedItem() != null) {
            out.println("Aggiungi");
            String contatto = contattiComboBox.getSelectedItem() + "";
            out.println(contatto);
            contattiComboBox.removeItem(contatto);
        }
    }//GEN-LAST:event_btnAggiungiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnInvia;
    private javax.swing.JComboBox<String> contattiComboBox;
    private javax.swing.JTextArea conversazione;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messaggio;
    // End of variables declaration//GEN-END:variables
}

