/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chattcp;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 * @author Piergiorgio Favaretto
 * @brief Classe che si occupa di gestire l'interfaccia grafica del client
 * effettua le operazioni di ascolto se arrivano dei dati da un altro utente
 * Attraverso la sottoclasse Ascoltatore
 * @date 10/11/2017
 * @version 1.0
 */
public class ClientFrame extends javax.swing.JFrame {

    private PrintWriter writer;
    private BufferedReader reader;
    private String messaggio = "", mex = "", nome;
    private DefaultListModel h;
    private String nomeSel, s;
    private ArrayList<String> connessi;

    private class Ascoltatore extends Thread {

        public void run() {
            String x = "";
            while (true) {
                try {
                    x = reader.readLine();
                    if (x.equals("#aggiornalalista")) {
                        connessi = new ArrayList<>();
                        while (!x.equals("#fineinviolistconnessi")) {
                            x = reader.readLine();
                            if (!x.equals("#fineinviolistconnessi")) {
                                connessi.add(x);
                            }
                        }
                        settaLista(connessi);
                    } else {
                        myLog("[" + nomeSel + "]: " + x + "\n");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(ClientFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void myLog(String message) {
        messaggio += message;
        chat.setText(messaggio);
    }

    private void settaLista(ArrayList<String> c) {
        h = new DefaultListModel();
        utenti.setModel(h);
        try {
            for (int i = 0; i < c.size(); i++) {
                s = c.get(i);
                if (!s.equals(nome)) {
                    h.addElement(s);
                }
            }
        } catch (Exception e) {
        }
    }

    public ClientFrame(BufferedReader reader, PrintWriter writer, String username) {
        super("Whatsappete");
        nome = username;
        this.writer = writer;
        this.reader = reader;
        initComponents();
        Ascoltatore a = new Ascoltatore();
        a.start();
        setVisible(true);
    }

    private void comunica() {
        mex = inserisci.getText().trim();
        writer.println(nomeSel);
        writer.println(mex);
        myLog("[Io]: " + mex + "\n");
    }

    private void settaNome(String sc) {
        this.nomeSel = sc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invia = new javax.swing.JButton();
        inserisci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextPane();
        esci = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        utenti = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        invia.setText("Invia");
        invia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Whatsappete");

        chat.setEditable(false);
        chat.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jScrollPane1.setViewportView(chat);

        esci.setText("Esci");
        esci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esciActionPerformed(evt);
            }
        });

        utenti.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        utenti.setToolTipText("");
        utenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utentiMouseClicked(evt);
                prova(evt);
            }
        });
        jScrollPane2.setViewportView(utenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(inserisci))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(esci)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invia)
                    .addComponent(inserisci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esci))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaActionPerformed
        comunica();
        inserisci.setText("");
    }//GEN-LAST:event_inviaActionPerformed

    private void esciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esciActionPerformed
        writer.println("#fine " + nome);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_esciActionPerformed

    private void utentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utentiMouseClicked
        int n = utenti.getSelectedIndex();
        h = (DefaultListModel) utenti.getModel();
        settaNome((String) h.getElementAt(n));
    }//GEN-LAST:event_utentiMouseClicked

    private void prova(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prova
        // TODO add your handling code here:
    }//GEN-LAST:event_prova

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextPane chat;
    private javax.swing.JButton esci;
    private static javax.swing.JTextField inserisci;
    private javax.swing.JButton invia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> utenti;
    // End of variables declaration//GEN-END:variables
}
