/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Enrico
 */
public class VistaUtente extends javax.swing.JFrame {

    private class Ascoltatore extends Thread {

        @Override
        public void run() {
            boolean continua = true;
            while (continua) {
                try {
                    String op = in.readLine();
                    if (op.equals("Errore")) {
                        labelErrori.setText("Contatto non valido");
                    } else if (op.equals("AggiungiChat")) {
                        JLabel labelChat = new JLabel(in.readLine());
                        labelChat.setAlignmentX(Component.CENTER_ALIGNMENT);
                        labelChat.addMouseListener(new AscoltatorePerChat(Integer.parseInt(in.readLine())));
                        panelChat.add(labelChat);
                        setVisible(true);
                    }else if(op.equals("CreaGruppo")){
                        continua=false;
                        dispose();
                        VistaCreazioneGruppo v=new VistaCreazioneGruppo(in,out);
                        v.setVisible(true);
                    }else if(op.equals("Chat")){
                        continua=false;
                        dispose();
                        VistaChat v=new VistaChat(in,out,Integer.parseInt(in.readLine()));
                        v.setVisible(true);
                    }else if (op.equals("")) {
                        continua = false;
                    }
                } catch (IOException ex) {
                    Logger.getLogger(VistaUtente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private BufferedReader in;
    private PrintWriter out;

    /**
     * Creates new form VistaUtente
     */
    public VistaUtente(BufferedReader in, PrintWriter out) throws IOException {
        this.in = in;
        this.out = out;
        initComponents();
        panelChat.setLayout(new BoxLayout(panelChat, BoxLayout.Y_AXIS));
        out.println("Carica");
		labelUsername.setText(in.readLine());
        int nChat = Integer.parseInt(in.readLine());
        for (int i = 0; i < nChat; i++) {
            JLabel labelChat = new JLabel(in.readLine());
            labelChat.setAlignmentX(Component.CENTER_ALIGNMENT);
            labelChat.addMouseListener(new AscoltatorePerChat(Integer.parseInt(in.readLine())));
            panelChat.add(labelChat);
        }
        new Ascoltatore().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEsci = new javax.swing.JButton();
        btnAggiungiContatto = new javax.swing.JButton();
        btnCreaGruppo = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelErrori = new javax.swing.JLabel();
        panelChat = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEsci.setText("Esci");
        btnEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsciActionPerformed(evt);
            }
        });

        btnAggiungiContatto.setText("Aggiungi contatto");
        btnAggiungiContatto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiContattoActionPerformed(evt);
            }
        });

        btnCreaGruppo.setText("Crea gruppo");
        btnCreaGruppo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaGruppoActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        panelChat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelChatLayout = new javax.swing.GroupLayout(panelChat);
        panelChat.setLayout(panelChatLayout);
        panelChatLayout.setHorizontalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        panelChatLayout.setVerticalGroup(
            panelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAggiungiContatto)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelErrori, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreaGruppo)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEsci)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEsci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAggiungiContatto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelErrori, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnCreaGruppo))
                    .addComponent(panelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        dispose();
        out.println("");
        VistaAutenticazione v = new VistaAutenticazione(in, out);
        v.setVisible(true);
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnAggiungiContattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiContattoActionPerformed
        labelErrori.setText("");
        out.println("AggiungiContatto");
        String user = username.getText();
        out.println(user);
    }//GEN-LAST:event_btnAggiungiContattoActionPerformed

    private void btnCreaGruppoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaGruppoActionPerformed
        out.println("CreaGruppo");
    }//GEN-LAST:event_btnCreaGruppoActionPerformed

    private class AscoltatorePerChat implements MouseListener {

        private int idChat;

        public AscoltatorePerChat(int idChat) {
            this.idChat = idChat;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            out.println("Chat");
            out.println(idChat);
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungiContatto;
    private javax.swing.JButton btnCreaGruppo;
    private javax.swing.JButton btnEsci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelErrori;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelChat;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
